equipment_conditions = {
    "A": "Working",
    "B": "Good/not in use",
    "C": "In use but need Repair",
    "D": "In use but need Replacement",
    "E": "Out of order/Repairable",
    "F": "Out of order/Replacement"
}

equipment_types = (
    "Air Compressor",
    "Air Conditioner",
    "Anesthesia Machine",
    "Aspirator/Suction Machine",
    "Autoclave (lab, surgery, and other)",
    "Automatic Voltage Regulator",
    "Bed, delivery",
    "Blood Bank Refrigerator",
    "Blood clotting time meter",
    "Blood electrolyte analyzer",
    "Blood Gas Analyzer",
    "Blood Pressure Device, Automatic (NIBP)",
    "Blood Pressure Device, Manual (Sphygmomanometer) (Fixed or portable)",
    "Bottle Washing Machine",
    "Breast Pump ",
    "Capnograph",
    "Ceiling Fan",
    "Centrifuge",
    "Centrifuge (electric or hand operated) ",
    "Change Over Switch",
    "Computer",
    "Control Switch Panel",
    "Defibrillator (automatic and manual)",
    "Dental Drilling Machine",
    "Dialysis Equipment",
    "Distiller",
    "Drying Machine",
    "ECG Machine",
    "Electrosurgery Unit (ESU)",
    "Fetal steth (fetoscope or  Doppler)",
    "Fluoroscopy (x-ray moving images)",
    "Furniture (chairs, tables, and beds)",
    "Generator",
    "Glucose level kit (or glucometer)",
    "Heart Lung Machine",
    "Hot Plate (laboratory, but not kitchen)",
    "Incubator (infant)",
    "Infant Warmer (radiant or other)",
    "Infusion pumps",
    "Iron (for clothing)",
    "Lamp, examination",
    "Lamp, surgical",
    "Laryngoscope",
    "Microscope ",
    "Nebulizer",
    "Operating Table",
    "Ophthalmoscope (eye examination instrument) ",
    "Otoscopes",
    "Oven (laboratory, not kitchen)",
    "Oxygen Concentrator",
    "Pacemaker (ext, temp and permanent)",
    "Patient Monitor",
    "Photocopier",
    "Phototherapy device",
    "Printer",
    "Projector",
    "Pulse Oximeter",
    "Respiration monitor (apnea monitor)",
    "Scales (laboratory and in wards)",
    "Shaker Machine (laboratory)",
    "Skin Grafting Machine (dermatome)",
    "Spectrophotometer/Colorimeter",
    "Stethoscopes",
    "Telephone",
    "Television",
    "Thermometers",
    "Transformer",
    "Ultrasound Machine (imaging)",
    "UPS (battery backup for computer)",
    "Vaccine Refrigerator",
    "Vacuum Extractor (for delivery)",
    "Ventilator",
    "Washing Machine",
    "Water Bath (laboratory)",
    "Water Pump (for drinking water)",
    "Water Purifier (for lab, in wards) ",
    "X-Ray Film Dryer",
    "X-Ray Film View Box",
    "X-Ray Machine",
    "Other"
)

problem_types = (
    "Plumbing",
    "Motor",
    "Electric",
    "Mechanical",
    "Power Supply",
    "Installation/Training",
    "Other"
)

job_types = {
    "Repair",
    "Preventative",
    "Installation/Training",
    "Other"
}

job_urgency = {
    1:"Emergency",
    2:"Urgent",
    3:"Normal",
    4:"Routine"
}